homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone

  customize: !include customize.yaml

# Enables support for tracking state changes over time.
recorder:
  # Delete events and states older than 1 weeks
  purge_interval: 2
  purge_keep_days: 7

emulated_hue:
  type: google_home
  listen_port: 80
  expose_by_default: false


# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  trusted_networks: !secret trusted_networks


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:
wemo:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant
  keepalive: 60
  username: user
  password: !secret mqtt_password
  protocol: 3.1.1


input_boolean:
  jimmy_left_work:
    name: Jimmy has left work
    initial: off
  jimmy_heading_home:
    name: Jimmy is heading home
    initial: off

input_number:
  strip1_animation_speed:
    name: Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10

notify:
  - name: daniel-phone
    platform: pushbullet
    api_key: !secret pushbullet_api_key

cover:
  platform: opengarage
  covers:
      garage:
        host: !secret opengarage_ip
        device_key: opendoor
        name: garage

xiaomi_aqara:
 gateways:
   - mac:
     key: !secret xiaomi_key

group: !include groups.yaml
sensor: !include sensors.yaml
#binary_sensor: !include binary_sensors.yaml
switch: !include switches.yaml
automation: !include automation.yaml
light: !include lights.yaml
