# Weather Prediction
- platform: darksky
  api_key: !secret darksky_api_key
  update_inverval:
    minutes: 10
  monitored_conditions:
    - summary
    - apparent_temperature
    - precip_type

- platform: mqtt
  name: "Laundry Dryer Power"
  unit_of_measurement: "W"
  state_topic: "tele/sonoff/laundry_dryer/ENERGY"
  value_template: '{{ value_json.Power | float }}'

- platform: mqtt
  name: "Laundry Washer Power"
  unit_of_measurement: "W"
  state_topic: "tele/sonoff/laundry_washer/ENERGY"
  value_template: '{{ value_json.Power | float }}'

- platform: template
  sensors:
    washer_status:
      friendly_name: 'Washer Status'
      value_template: "{% if states.sensor.laundry_washer_power.state | float > 6 %}In Use{% elif states.sensor.laundry_washer_power.state | float < 6 %}Standby{% else %}Unknown{% endif %}"
    dryer_status:
      friendly_name: 'Dryer Status'
      value_template: "{% if states.sensor.laundry_dryer_power.state | float > 6 %}In Use{% elif states.sensor.laundry_dryer_power.state | float < 6 %}Standby{% else %}Unknown{% endif %}"

- platform: template
  sensors:
    garage_status:
      friendly_name: 'Garage Door Status'
      value_template: '{% if states.cover.garage %}
          {% if states.cover.garage.attributes["door_state"] == "open" %}
            Open
          {% elif states.cover.garage.attributes["door_state"] == "closed" %}
            Closed
          {% elif states.cover.garage.attributes["door_state"] == "opening" %}
            Opening
          {% elif states.cover.garage.attributes["door_state"] == "closing" %}
            Closing
          {% else %}
            Unknown
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
    garage_car_present:
      friendly_name: 'Car in Garage'
      value_template: '{% if states.cover.garage %}
          {% if states.cover.garage.state == "open" %}
            n/a
          {% elif ((states.cover.garage.attributes["distance_sensor"] > 40) and (states.cover.garage.attributes["distance_sensor"] < 100)) %}
            Yes
          {% else %}
            No
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
