- platform: mqtt
  name: "Laundry Dryer"
  state_topic: "stat/sonoff/laundry_dryer/POWER"
  command_topic: "cmnd/sonoff/laundry_dryer/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Laundry Washer"
  state_topic: "stat/sonoff/laundry_washer/POWER"
  command_topic: "cmnd/sonoff/laundry_washer/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

